// Default parameter
params {
    no_trim = false // No default, must be specified
    kit_name = null // No default, must be specified
    min_qscore = 0 // Default minimum Q-score
    barcode_both_ends = false
    emit_fastq = false // No default, must be specified
    input_dir = "${projectDir}/data" // Default input directory
    output_dir = "${projectDir}/output" // Default output directory
}

// Process-level configurations
process {
    withName: dorado_basecalling {
        cpus = 4
        memory = '8 GB'
        time = '8h'
    }
    withName: 'dorado_demultiplex' {
        cpus = 4
        memory = '8 GB'
        time = '4h'
    }
}

// Executor settings
    executor {
        name = 'local'
        queueSize = 10
}
workDir = './work'
